#![forbid(unsafe_code)]

use pipe_sim::{
    observed_manipulation::{
        M1eFault, ObservedManipulationRuntime as NativeObservedManipulationRuntime, ScenarioError,
        M1E_SCENARIO_SCHEMA_VERSION, OBSERVED_MANIPULATION_REPORT_SCHEMA_VERSION,
    },
    optical_codesign_report, PointMotionRuntime as NativePointMotionRuntime,
    ReferenceSimulator as NativeSimulator, ScenarioSpec,
    SimpleManipulationRuntime as NativeSimpleManipulationRuntime, REPORT_SCHEMA_VERSION,
    SCENE_SCHEMA_VERSION,
};
use pipe_sim_core::{ManipulatorId, Vec3};
use wasm_bindgen::prelude::*;

pub const WASM_API_SCHEMA_VERSION: u32 = REPORT_SCHEMA_VERSION;
const DEFAULT_MAX_CYCLES: u32 = 12_000;
const DEFAULT_MAX_POINT_MOTION_STEPS: u32 = 20_000;
const DEFAULT_MAX_MANIPULATION_STEPS_PER_ACTION: u32 = 20_000;

fn js_error(error: impl std::fmt::Display) -> JsValue {
    JsValue::from_str(&error.to_string())
}

/// Static M1d trade-study report generated by the same Rust implementation as
/// the headless CLI. Its status deliberately remains hardware-unqualified.
#[wasm_bindgen(js_name = opticalCodesignReportJson)]
pub fn optical_codesign_report_json(pretty: bool) -> Result<String, JsValue> {
    optical_codesign_report()
        .and_then(|report| report.to_json(pretty))
        .map_err(js_error)
}

/// Browser-safe wrapper around the same deterministic simulator used by the
/// headless CLI. JSON is used intentionally so the website can retain report
/// snapshots across WASM schema upgrades without exposing Rust object layouts.
#[wasm_bindgen(js_name = ReferenceSimulator)]
pub struct WasmReferenceSimulator {
    inner: NativeSimulator,
}

/// Standalone M1b browser runtime. This deliberately excludes the legacy
/// gearbox executive so it cannot overwrite a Cartesian calibration command.
#[wasm_bindgen(js_name = PointMotionSimulator)]
pub struct WasmPointMotionSimulator {
    inner: NativePointMotionRuntime,
}

/// Standalone M1c calibration-peg runtime. Grasp ownership and the attached
/// part pose remain inside the Rust plant throughout the cycle.
#[wasm_bindgen(js_name = SimpleManipulationSimulator)]
pub struct WasmSimpleManipulationSimulator {
    inner: NativeSimpleManipulationRuntime,
}

/// M1e observed-state manipulation runtime. The WASM boundary accepts only a
/// versioned scenario document (when explicitly supplied) and a named fault;
/// all observation, estimation, guard, and report logic remains in Rust.
#[wasm_bindgen(js_name = ObservedManipulationSimulator)]
pub struct WasmObservedManipulationSimulator {
    inner: NativeObservedManipulationRuntime,
}

#[wasm_bindgen(js_class = ObservedManipulationSimulator)]
impl WasmObservedManipulationSimulator {
    /// Construct the checked-in baseline scenario. Omit `fault` (or pass
    /// `"none"`/`"nominal"`) for the nominal deterministic run.
    #[wasm_bindgen(constructor)]
    pub fn new(fault: Option<String>) -> Result<WasmObservedManipulationSimulator, JsValue> {
        let fault = parse_m1e_fault(fault.as_deref()).map_err(js_error)?;
        Ok(Self {
            inner: NativeObservedManipulationRuntime::new(fault).map_err(js_error)?,
        })
    }

    /// Construct from an explicit versioned M1e scenario JSON document.
    #[wasm_bindgen(js_name = fromScenarioJson)]
    pub fn from_scenario_json(
        scenario_json: &str,
        fault: Option<String>,
    ) -> Result<WasmObservedManipulationSimulator, JsValue> {
        let fault = parse_m1e_fault(fault.as_deref()).map_err(js_error)?;
        Ok(Self {
            inner: NativeObservedManipulationRuntime::from_scenario_json(scenario_json, fault)
                .map_err(js_error)?,
        })
    }

    /// Execute the complete fixed-step M1e vertical slice once.
    #[wasm_bindgen(js_name = runCycleJson)]
    pub fn run_cycle_json(&mut self, pretty: bool) -> Result<String, JsValue> {
        self.inner
            .run_cycle()
            .and_then(|report| report.to_json(pretty))
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = reportJson)]
    pub fn report_json(&self, pretty: bool) -> Result<String, JsValue> {
        self.inner.report().to_json(pretty).map_err(js_error)
    }

    #[wasm_bindgen(getter, js_name = terminal)]
    pub fn terminal(&self) -> bool {
        self.inner.is_terminal()
    }

    #[wasm_bindgen(getter, js_name = completed)]
    pub fn completed(&self) -> bool {
        self.inner.is_completed()
    }

    #[wasm_bindgen(getter, js_name = status)]
    pub fn status(&self) -> String {
        self.inner.report().status.to_owned()
    }

    #[wasm_bindgen(getter, js_name = controllerReportSha256)]
    pub fn controller_report_sha256(&self) -> String {
        self.inner.report().controller_report_sha256
    }
}

fn parse_m1e_fault(value: Option<&str>) -> Result<M1eFault, ScenarioError> {
    value.unwrap_or("none").parse()
}

#[wasm_bindgen(js_class = SimpleManipulationSimulator)]
impl WasmSimpleManipulationSimulator {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Result<WasmSimpleManipulationSimulator, JsValue> {
        Ok(Self {
            inner: NativeSimpleManipulationRuntime::new().map_err(js_error)?,
        })
    }

    #[wasm_bindgen(js_name = runCycleJson)]
    pub fn run_cycle_json(&mut self, max_steps_per_action: u32) -> Result<String, JsValue> {
        let limit = if max_steps_per_action == 0 {
            DEFAULT_MAX_MANIPULATION_STEPS_PER_ACTION
        } else {
            max_steps_per_action
        };
        self.inner
            .run_cycle(limit)
            .and_then(|report| report.to_json(false))
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = reportJson)]
    pub fn report_json(&self, pretty: bool) -> Result<String, JsValue> {
        self.inner.report().to_json(pretty).map_err(js_error)
    }

    #[wasm_bindgen(js_name = sceneDescriptionJson)]
    pub fn scene_description_json(&self) -> Result<String, JsValue> {
        self.inner.scene_description_json(false).map_err(js_error)
    }

    #[wasm_bindgen(js_name = sceneFrameJson)]
    pub fn scene_frame_json(&self) -> Result<String, JsValue> {
        self.inner.scene_frame_json(false).map_err(js_error)
    }

    #[wasm_bindgen(getter, js_name = terminal)]
    pub fn terminal(&self) -> bool {
        self.inner.is_terminal()
    }

    #[wasm_bindgen(getter, js_name = completed)]
    pub fn completed(&self) -> bool {
        self.inner.is_completed()
    }
}

#[wasm_bindgen(js_class = PointMotionSimulator)]
impl WasmPointMotionSimulator {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Result<WasmPointMotionSimulator, JsValue> {
        Ok(Self {
            inner: NativePointMotionRuntime::new().map_err(js_error)?,
        })
    }

    #[wasm_bindgen(js_name = setToolTarget)]
    pub fn set_tool_target(
        &mut self,
        manipulator_id: u32,
        x_m: f64,
        y_m: f64,
        z_m: f64,
    ) -> Result<u64, JsValue> {
        self.inner
            .submit_tool_target(ManipulatorId(manipulator_id), Vec3::new(x_m, y_m, z_m))
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = setCalibrationTarget)]
    pub fn set_calibration_target(&mut self) -> Result<u64, JsValue> {
        self.inner.submit_calibration_target().map_err(js_error)
    }

    #[wasm_bindgen(js_name = stepJson)]
    pub fn step_json(&mut self) -> Result<String, JsValue> {
        self.inner.step().map_err(js_error)?;
        self.inner.scene_frame_json(false).map_err(js_error)
    }

    #[wasm_bindgen(js_name = runUntilSettledJson)]
    pub fn run_until_settled_json(&mut self, max_steps: u32) -> Result<String, JsValue> {
        let limit = if max_steps == 0 {
            DEFAULT_MAX_POINT_MOTION_STEPS
        } else {
            max_steps
        };
        self.inner
            .run_until_settled(limit)
            .and_then(|report| report.to_json(false))
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = runCalibrationCycleJson)]
    pub fn run_calibration_cycle_json(
        &mut self,
        max_steps_per_leg: u32,
    ) -> Result<String, JsValue> {
        let limit = if max_steps_per_leg == 0 {
            DEFAULT_MAX_POINT_MOTION_STEPS
        } else {
            max_steps_per_leg
        };
        self.inner
            .run_calibration_cycle(limit)
            .and_then(|report| report.to_json(false))
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = reportJson)]
    pub fn report_json(&self, pretty: bool) -> Result<String, JsValue> {
        self.inner.report().to_json(pretty).map_err(js_error)
    }

    #[wasm_bindgen(js_name = sceneDescriptionJson)]
    pub fn scene_description_json(&self) -> Result<String, JsValue> {
        self.inner.scene_description_json(false).map_err(js_error)
    }

    #[wasm_bindgen(js_name = sceneFrameJson)]
    pub fn scene_frame_json(&self) -> Result<String, JsValue> {
        self.inner.scene_frame_json(false).map_err(js_error)
    }

    #[wasm_bindgen(getter, js_name = active)]
    pub fn active(&self) -> bool {
        self.inner.is_active()
    }
}

#[wasm_bindgen(js_class = ReferenceSimulator)]
impl WasmReferenceSimulator {
    #[wasm_bindgen(constructor)]
    pub fn new(scenario: Option<String>) -> Result<WasmReferenceSimulator, JsValue> {
        let scenario = scenario.as_deref().unwrap_or("nominal");
        let inner = NativeSimulator::from_scenario_name(scenario).map_err(js_error)?;
        Ok(Self { inner })
    }

    /// Advance exactly one 20 ms executive cycle and return its full snapshot.
    #[wasm_bindgen(js_name = stepJson)]
    pub fn step_json(&mut self) -> Result<String, JsValue> {
        self.inner
            .step()
            .map_err(js_error)?
            .to_json(false)
            .map_err(js_error)
    }

    /// Run until assembly completes/aborts, using 12k cycles when zero is passed.
    #[wasm_bindgen(js_name = runToCompletionJson)]
    pub fn run_to_completion_json(&mut self, max_cycles: u32) -> Result<String, JsValue> {
        let limit = if max_cycles == 0 {
            DEFAULT_MAX_CYCLES
        } else {
            max_cycles
        };
        self.inner
            .run_to_completion(limit)
            .map_err(js_error)?
            .to_json(false)
            .map_err(js_error)
    }

    #[wasm_bindgen(js_name = reportJson)]
    pub fn report_json(&self, pretty: bool) -> Result<String, JsValue> {
        self.inner.report_json(pretty).map_err(js_error)
    }

    /// Static geometry/topology/configuration. Fetch once per simulator reset.
    #[wasm_bindgen(js_name = sceneDescriptionJson)]
    pub fn scene_description_json(&self) -> Result<String, JsValue> {
        self.inner.scene_description_json(false).map_err(js_error)
    }

    /// Current physical/estimated/commanded layers without advancing time.
    #[wasm_bindgen(js_name = sceneFrameJson)]
    pub fn scene_frame_json(&self) -> Result<String, JsValue> {
        self.inner.scene_frame_json(false).map_err(js_error)
    }

    #[wasm_bindgen(getter, js_name = terminal)]
    pub fn terminal(&self) -> bool {
        self.inner.is_terminal()
    }

    #[wasm_bindgen(getter, js_name = completed)]
    pub fn completed(&self) -> bool {
        self.inner.is_completed()
    }

    #[wasm_bindgen(getter, js_name = scenario)]
    pub fn scenario(&self) -> String {
        self.inner.scenario_spec().name.clone()
    }
}

#[wasm_bindgen(js_name = runReferenceScenario)]
pub fn run_reference_scenario(scenario: &str, max_cycles: u32) -> Result<String, JsValue> {
    let mut simulator = NativeSimulator::from_scenario_name(scenario).map_err(js_error)?;
    let limit = if max_cycles == 0 {
        DEFAULT_MAX_CYCLES
    } else {
        max_cycles
    };
    simulator
        .run_to_completion(limit)
        .map_err(js_error)?
        .to_json(false)
        .map_err(js_error)
}

#[wasm_bindgen(js_name = availableScenariosJson)]
pub fn available_scenarios_json() -> String {
    let values = ScenarioSpec::available()
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(",");
    format!("[{values}]")
}

#[wasm_bindgen(js_name = reportSchemaVersion)]
pub fn report_schema_version() -> u32 {
    REPORT_SCHEMA_VERSION
}

#[wasm_bindgen(js_name = sceneSchemaVersion)]
pub fn scene_schema_version() -> u32 {
    SCENE_SCHEMA_VERSION
}

#[wasm_bindgen(js_name = observedManipulationReportSchemaVersion)]
pub fn observed_manipulation_report_schema_version() -> u32 {
    OBSERVED_MANIPULATION_REPORT_SCHEMA_VERSION
}

#[wasm_bindgen(js_name = observedManipulationScenarioSchemaVersion)]
pub fn observed_manipulation_scenario_schema_version() -> u32 {
    M1E_SCENARIO_SCHEMA_VERSION
}

/// The historical singular getters describe the default M1e adapter. Explicit
/// scenario JSON can select M1f; both scenario and report versions are listed.
#[wasm_bindgen(js_name = observedManipulationSupportedSchemaVersionsJson)]
pub fn observed_manipulation_supported_schema_versions_json() -> String {
    "{\"scenario\":[1,2],\"report\":[1,2]}".to_owned()
}

#[wasm_bindgen(js_name = availableObservedManipulationFaultsJson)]
pub fn available_observed_manipulation_faults_json() -> String {
    let values = M1eFault::available()
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(",");
    format!("[{values}]")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scenario_listing_is_json() {
        assert_eq!(
            available_scenarios_json(),
            "[\"gearbox_baseline_v1\",\"nominal\",\"collision\",\"occlusion\",\"insertion-force\",\"fault-suite\"]"
        );
    }

    #[test]
    fn schema_versions_match() {
        assert_eq!(report_schema_version(), pipe_sim::REPORT_SCHEMA_VERSION);
        assert_eq!(scene_schema_version(), pipe_sim::SCENE_SCHEMA_VERSION);
        assert_eq!(
            observed_manipulation_report_schema_version(),
            pipe_sim::observed_manipulation::OBSERVED_MANIPULATION_REPORT_SCHEMA_VERSION
        );
        assert_eq!(
            observed_manipulation_scenario_schema_version(),
            pipe_sim::observed_manipulation::M1E_SCENARIO_SCHEMA_VERSION
        );
    }

    #[test]
    fn m1e_fault_listing_and_default_runtime_are_stable() {
        assert_eq!(
            available_observed_manipulation_faults_json(),
            "[\"none\",\"optical_dropout\",\"excessive_calibration_bias\",\"stale_observation\",\"correction_floor_too_large\",\"grasp_outside_capture\",\"insertion_jam\",\"occluded_mating_feature\",\"carried_part_collision\",\"inconsistent_observation\",\"non_convergence\"]"
        );
        assert_eq!(parse_m1e_fault(None).unwrap(), M1eFault::None);
        assert_eq!(parse_m1e_fault(Some("nominal")).unwrap(), M1eFault::None);

        let runtime = WasmObservedManipulationSimulator::new(None).unwrap();
        assert_eq!(runtime.status(), "ready");
        assert!(!runtime.terminal());
        assert!(!runtime.completed());
        assert_eq!(runtime.controller_report_sha256().len(), 64);
        let ready_json = runtime.report_json(false).unwrap();
        assert!(ready_json.contains("\"schema_version\":1"));
        assert!(ready_json.contains("\"evaluation_only_truth\":null"));
    }

    #[test]
    fn m1e_host_wrapper_preserves_deterministic_report() {
        let mut first = WasmObservedManipulationSimulator::new(None).unwrap();
        let mut second = WasmObservedManipulationSimulator::new(Some("none".to_owned())).unwrap();
        let first_json = first.run_cycle_json(false).unwrap();
        let second_json = second.run_cycle_json(false).unwrap();

        assert_eq!(first_json, second_json);
        assert!(first_json.contains("\"source\":\"direct_feature_fit\""));
        assert!(first_json.contains("\"source\":\"held_transform_from_fresh_tool\""));
        assert_eq!(
            first.controller_report_sha256(),
            second.controller_report_sha256()
        );
        assert_eq!(first.status(), "complete");
        assert!(first.completed());
        assert!(first.terminal());
    }
}
